name: CI Pipeline con Pruebas

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas automatizadas (Quality Gate)
        run: npm test

      - name: Guardar reporte de cobertura
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reporte-cobertura
          path: coverage/